<?php

include($_SERVER['DOCUMENT_ROOT'].'/main_action.php');

$site_title = "Cleaning Services";
$site_description = "Learn about our various upholstery and carpet cleaning services in NYC for all types of textiles including rugs, couches, mattresses, vehicles, oriental rugs, and more!";
$canonical = $site_canonical;
$site_keywords = "";
$og_site_title = "";
$og_description = "";
$og_title = "";
$og_url = "";
$og_image = "";
$ld_json = <<<LD_JSON

LD_JSON;

?>
<?php
    $bodyClass = 'service-template-default single single-service postid-2538 group-blog';
    include ($_SERVER['DOCUMENT_ROOT'].'/header-optimize.php');
?>



<style>
/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on August 10, 2022 */



@font-face {
    font-family: 'latohairline_italic';
    src: url('lato-thinitalic-webfont.woff2') format('woff2'),
         url('lato-thinitalic-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latohairline';
    src: url('lato-thin-webfont.woff2') format('woff2'),
         url('lato-thin-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latoregular';
    src: url('lato-regular-webfont.woff2') format('woff2'),
         url('lato-regular-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latolight_italic';
    src: url('lato-lightitalic-webfont.woff2') format('woff2'),
         url('lato-lightitalic-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latolight';
    src: url('lato-light-webfont.woff2') format('woff2'),
         url('lato-light-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latoitalic';
    src: url('lato-italic-webfont.woff2') format('woff2'),
         url('lato-italic-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latobold_italic';
    src: url('lato-bolditalic-webfont.woff2') format('woff2'),
         url('lato-bolditalic-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latobold';
    src: url('lato-bold-webfont.woff2') format('woff2'),
         url('lato-bold-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latoblack_italic';
    src: url('lato-blackitalic-webfont.woff2') format('woff2'),
         url('lato-blackitalic-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}




@font-face {
    font-family: 'latoblack';
    src: url('lato-black-webfont.woff2') format('woff2'),
         url('lato-black-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

.fa{
	display:inline-block;
	font:normal normal normal 14px/1 latolight;
	font-size:inherit;
	text-rendering:auto;
	-webkit-font-smoothing:antialiased;
	-moz-osx-font-smoothing:grayscale
}
.fab{
	display:inline-block;
	font:normal normal normal 14px/1 latolight_italic;
	font-size:inherit;
	text-rendering:auto;
	-webkit-font-smoothing:antialiased;
	-moz-osx-font-smoothing:grayscale
}
.far{
	display:inline-block;
	font:normal normal normal 14px/1 latoblack_italic;
	font-size:inherit;
	text-rendering:auto;
	-webkit-font-smoothing:antialiased;
	-moz-osx-font-smoothing:grayscale
}
.fa-fw{
	width:1.28571429em;
	text-align:center
}

</style>
      <section id="top-banner" class="position-relative">
          <img rel="canonical" class="img lazy" data-src="/assets/images/service/carpet-cleaning-services-NYC-banner-Top.webp" width="1920" height="590">
          <div class="banner-content container-fluid padding-0 position-absolute w-100 py-7">
              <div class="container">
                  <div class="row">
                      <div class="col-md-12 col-sm-12 col-xs-12">
                          <div class="heading-text services-heading">
                              <h1>Construction Services</h1>
                              <h4>Essential Construction and Remodel Services</h4>
                          </div>
                      </div>
                      <div class="text-left pb-3">
                          <a href="tel:3478716530" class="btn callnow-btn center ml-0">Call Now</a>
                          <a href="/contact-us#contact-form-fields" class="btn emailnow-btn center">Email Now</a>
                      </div>
                  </div>
              </div>
          </div>
      </section>

      <section id="main-content-cleaning" class="py-7 main-content-cleaning-service">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                   <div class="section-header text-center pb-4">
                       <h2 class="lh-1-3 lh-md-auto fs-1 fs-md-3 mb-3 text-green text-uppercase">Services</h2>
                   </div>
                  <div class="services-items col-md-12 row">
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/carpet-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/carpet-cleaner-nyc.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Bathroom Remodel</h4>
                           <p class="paragraph">Every so often, your car needs a full service car wash to protect the paint and finish  and deep clean the interior of your car with professional uphosltery cleaning machines, tools, and chemicals. </p>
                        </a>
                     </div>
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/upholstery-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/upholstery-cleaning-nyc.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Home Renovation</h4>
                           <p class="paragraph">Our cars are like second homes so treat your car to an auto spa. Detail, protect, and shine the exterior of your vehicle and pamper the interior fabrics, plastics, and leather to preserve and bring the best out of your vehicle.</p>
                        </a>
                     </div>
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/area-rug-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/rug-cleaning-ny.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Car Seat Cleaning and Shampoo</h4>
                           <p class="paragraph">Accidents happen but its important to clean them up promply! Use our car seat cleaning and shampoo service to remove tough stains out of fabric and leather.</p>
                        </a>
                     </div>
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/mattress-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/mattress-cleaner-nyc.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Interior Auto Detailing</h4>
                           <p class="paragraph">Ther interior of a car gets the most abuse from food bits, drink spills, and general dirt and grime. Clean and preserve your interior with an interior detail. We professional upholstery cleaning tools and chemicals to bring your interior back to new!</p>
                        </a>
                     </div>
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/oriental-rug-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/oriental-rug-cleaner-nyc.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Hand Car Wash</h4>
                           <p class="paragraph">Automatic car washes scratch your paint and damage your car! Opt for a hand car wash that preserves the paint, and protects the finish with a was or sealant. </p>
                           </a>
                     </div>
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/green-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/green-upholstery-carpet-cleaner-nyc.webp" width="295" height="295" alt="green carpet cleaner service">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Car Polish and Wax</h4>
                           <p class="paragraph">The exterior of the car is subjected to the elements 24/7. Every so often, you will need a car polish to remove scratches and swirls, and protect the paint from further damage with a wax. Keep your car looking great for longer with a polish and wax!</p>
                           </a>
                     </div>

                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/commercial-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/commerical-cleaning-nyc.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Paint Correction</h4>
                           <p class="paragraph">Sometimes we get scratches that really diminish from the overall appearance of the vehicle. In this case, get a paint correction treatment which removes scratches and protects your paint from future damage!</p>
                        </a>
                     </div>
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/couch-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/sofa-cleaning-nyc.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Car Deep Cleaning</h4>
                           <p class="paragraph">Cars have a lot of crevices and crannies and its important if you want your car to look fantastic to get a car deep cleaning. This services will deep clean your interior and exterior, and bring it to like new levels! </p>
                        </a>
                     </div>
                     <div class="col-12 col-sm-6 col-md-4 item">
                        <a href="/services/auto-interior-cleaning/">
                           <div class="top-holder">
                              <div class="img-holder">
                                 <img class="img img-fluid lazy" data-src="/assets/images/service/auto-interior-detailing-nyc.webp" width="295" height="295">
                              </div>
                           </div>
                           <h4 class="heading fw-bold fs-3 fs-md-5 lh-1-3 lh-md-auto">Truck Detailing</h4>
                           <p class="paragraph">Our trucks can get a lot of abuse from showing up at work sites and also having your employees use them all day every day. Preserve your truck with a truck detail and bring your interior and exterior back up to a pristine level!</p>
                        </a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>

      <section id="offering-services">
         <div class="container">
            <div class="row">
               <div class="col-12 col-md-8 text-center">
                   <div class="slider-content">
                       <div class='beforeAfterContainer'>
                           <div class='img background-img'></div>
                           <div class='img foreground-img'></div>
                           <input type="range" min="1" max="100" value="50" class="bslider" name='slider' id="bslider">
                           <div class='slider-button'></div>
                       </div>
                   </div>
               </div>
               <div class="col-12 col-md-4 text-center">
                  <br>
                  <br>
                  <br>
                  <br>
                  <div class="right-image"><img class="img-fluid lazy" data-src="/assets/images/Green-Carpet-Cleaning-Van-NYC-small.webp" alt="" width="420" height="221"></div>
						<a href="tel:3478716530" class="btn callnow-btn center offer-call">Call Now</a>
               </div>
            </div>
         </div>
		  
      </section>
	  <style>
* {box-sizing: border-box;}

.form-inline {  
  display: flex;
  flex-flow: row wrap;
  align-items: center;
}

.form-inline h4 {
  margin: 5px 10px 5px 0;
}

.form-inline input {
  vertical-align: middle;
  margin: 5px 10px 5px 0;
  padding: 10px;
  background-color: #fff;
  border: 1px solid #ddd;
}

.form-inline button {
	height: 40px !important;
	min-height: 40px;
  	padding: 10px;
  	background-color: dodgerblue;
  	color: white;
  	cursor: pointer;
	margin-top: 6px;
}

.form-inline button:hover {
  background-color: royalblue;
}
</style>
<header>
	<div class="callback-form-bar form-inline">
		<h4 style="margin: 7px 10px 5px 0; color:#fff;">Request Carpet and Upholstery Cleaning Now!</h4>
		<form method="post" class="header-form" style="margin: 7px 10px 5px 0;">
			<div class="form-group" style="width: 100%; display: flex;">
				<input class="form-control" type="text" name="your-number" placeholder="Phone number" required="" style="margin-left: 10px;">
				&nbsp;
				<input class="form-control" type="text" name="need-service" placeholder="Item to Clean" required="" style="margin-left: 10px;">
				&nbsp;
				<button class="btn btn-success" type="submit" name="request-callback" aria-label="Request callback" style="background-color:#4873b7; margin-left: 10px;" >Request</button>
			</div>
		</form>
	</div>
</header>
<style>
	.callback-form-bar {
		display: flex;
		justify-content: space-between !important;
		padding: 15px;
		background: #2baf38;
		border-radius: 10px;
		flex-direction: column;
		margin-bottom: 15px;
		display: flex;
		justify-content: center !important;
		align-items: center;
		
	}
	.form-inline {
	  display: flex;
	  flex-flow: row wrap;
	  align-items: center;
	}
	.callback-form-bar .header-form {
		flex-basis: 50%;
	}
	*, ::after, ::before {
		box-sizing: border-box;
	}
	*, ::after, ::before, input[type="checkbox"], input[type="radio"] {
		-webkit-box-sizing: border-box;
		-moz-box-sizing: border-box;
	}
	@media (max-width: 800px) {
	  .form-inline input {
		margin: 7px 0;
	  }

	  .form-inline {
		flex-direction: column;
		align-items: stretch;
	  }
	}
	.callback-form-bar {
		border-radius: 0px !important;
	}
</style>
      <?php
        $pg_images = array(
          array(
            'url' => 'Queens%20Carpet%20Cleaner%20Service%20PristineGreen%20Upholstery%20and%20Carpet%20Cleaning%2011105%20residential%20carpet%20cleaning.webp',
            'alt' => 'Queens Carpet Cleaner',
            'w' => 345,
            'h' => 259,
          ),
          array(
            'url' => 'sofa%20cleaning%20NYC%2010010%20NY%20New%20York%20couch%20cleaner%20NYC%20PristineGreen%20Upholstery%20and%20Carpet%20Cleaning.webp',
            'alt' => 'Upholstery and Carpet Cleaning',
            'w' => 345,
            'h' => 259,
          ),
          array(
            'url' => 'New%20York%20Carpet%20Cleaner%20Service%20PristineGreen%20Upholstery%20and%20Carpet%20Cleaning%2010010%20carpet%20upholstery%20cleaning.webp',
            'alt' => 'Upholstery Cleaning',
            'w' => 345,
            'h' => 214,
          ),
          array(
            'url' => '10010%20area%20rug%20cleaning%20nyc%20New%20York%20NY%20PristineGreen%20Upholstery%20and%20Carpet%20Cleaning%20rug%20cleaner%20nyc.webp',
            'alt' => 'Area Rug Cleaning',
            'w' => 345,
            'h' => 259,
          ),
          array(
            'url' => 'mattress%20cleaner%20nyc%20PristineGreen%20Upholstery%20and%20Carpet%20Cleaning%20upholstery%20cleaning%20nyc%20NY%20Queens%2011105.webp',
            'alt' => 'Mattress Cleaning',
            'w' => 345,
            'h' => 230,
          ),
          array(
            'url' => 'carpet%20cleaner%20service%20carpet%20shampoo%20Queens%20PristineGreen%20Upholstery%20and%20Carpet%20Cleaning%2011385%20NY.webp',
            'alt' => 'Carpet shampoo Queens',
            'w' => 345,
            'h' => 462,
          ),
        )
      ?>
      <?php include($_SERVER['DOCUMENT_ROOT'].'/partials/page-slider.php'); ?>

    <?php
        include ($_SERVER['DOCUMENT_ROOT'].'/partials/call-section.php');
        include ($_SERVER['DOCUMENT_ROOT'].'/partials/footer-top.php');
        include ($_SERVER['DOCUMENT_ROOT'].'/footer-optimize.php');
    ?>
