
		<?php $is_closed = isset($_COOKIE["close_action"]);  ?>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="module" src="<?= $baseUrl ?>/assets/js/fontAw.min.js" defer></script>
		<div class="header-nav" style="padding-top:0rem;">
			<style>
				.text-style {
					color: #4873b7;
				}
				
				#blog-detail-content h4 {
					color: #fff;
				}
				
				
				#blog-detail-content .header-form .btn {
					background-color: #2baf38 !important;
				}
				
				
				.accordion-header {
					border-top-right-radius: 13px !important;
					border-top-left-radius: 13px !important;
					border-bottom-right-radius: 13px !important;
					border-bottom-left-radius: 13px !important;
				}
				
				.ubermenu-autoclear {
					background: #2baf38 !important;
				}
				
				
				
				/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on August 10, 2022 */



				@font-face {
					font-family: 'latohairline_italic';
					src: url('/../assets/fonts/lato/lato-thinitalic-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-thinitalic-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latohairline';
					src: url('/../assets/fonts/lato/lato-thin-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-thin-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latoregular';
					src: url('/../assets/fonts/lato/lato-regular-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-regular-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latolight_italic';
					src: url('/../assets/fonts/lato/lato-lightitalic-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-lightitalic-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latolight';
					src: url('/../assets/fonts/lato/lato-light-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-light-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latoitalic';
					src: url('/../assets/fonts/lato/lato-italic-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-italic-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latobold_italic';
					src: url('/../assets/fonts/lato/lato-bolditalic-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-bolditalic-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latobold';
					src: url('/../assets/fonts/lato/lato-bold-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-bold-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latoblack_italic';
					src: url('/../assets/fonts/lato/lato-blackitalic-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-blackitalic-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}




				@font-face {
					font-family: 'latoblack';
					src: url('/../assets/fonts/lato/lato-black-webfont.woff2') format('woff2'),
						 url('/../assets/fonts/lato/lato-black-webfont.woff') format('woff');
					font-weight: normal;
					font-style: normal;

				}
				body, h2, h3, h4, h5, span{
				  font-family: latoregular !important;
				}
				
				.header-nav {
					top: 0px;
				}
				#bgimage-blog-detail {
				  margin-top: 54px;
				}
				
				
			</style>
			<div class="container">
			   <div class="col-md-3 col-sm-3 col-xs-3"><a class="navbar-brand logo-dark logo" href="/"><img src="/assets/logo/CarpetAndUpholsteryCleaning.png" class="main-logo" alt="#" height="90" width="266"></a></div>
			   <div class="col-md-9 col-sm-12 col-xs-12">
				  <div class="top-phone">
					 <div class="myphone">
						<h3><a class="myphone" href="tel:347-871-6530" style="color:#76D381"><img width="35" height="35" src="https://pristinegreencleaning.com/assets/icons/call.png"> 347-871-6530</a></h3>
					 </div>
					 
				  </div>
			   </div>
			   <div class="navbar1">
				  <br><br><button class="ubermenu-responsive-toggle ubermenu-responsive-toggle-main ubermenu-skin-none ubermenu-loc-primary" data-ubermenu-target="ubermenu-main-184-primary" type="button" aria-label="Options" ><i class='fa'>&#xf0c9;</i></button>
				  <nav id="ubermenu-main-184-primary" class="ubermenu ubermenu-main ubermenu-menu-184 ubermenu-loc-primary ubermenu-responsive ubermenu-responsive-991 ubermenu-responsive-collapse ubermenu-horizontal ubermenu-transition-fade ubermenu-trigger-hover ubermenu-skin-none  ubermenu-bar-align-full ubermenu-items-align-right ubermenu-bound ubermenu-disable-submenu-scroll ubermenu-sub-indicators ubermenu-retractors-responsive ubermenu-notouch" style="">
					 <ul id="ubermenu-nav-main-184-primary" class="ubermenu-nav">
						<!--<li id="menu-item-2459" class="quote_item ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-2459 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="/service" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Cleaning Services</span></a></li>

						<li id="menu-item-1742" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-home ubermenu-current-menu-item ubermenu-page_item ubermenu-page-item-2 ubermenu-current_page_item ubermenu-item-has-children ubermenu-item-1742 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega">
						-->
						<li id="menu-item-1742" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-home ubermenu-current-menu-item ubermenu-page_item ubermenu-page-item-2 ubermenu-current_page_item ubermenu-item-has-children ubermenu-item-1742 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto">
						   <span class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only border-megamenu" tabindex="0">
							   <a href="/services/" class="ubermenu-target-title ubermenu-target-text">Cleaning Services</a> <span class="ubermenu-toggler" data-toggleto="#menu-item-1742"></span>
							</span>
						   <ul class="ubermenu-submenu ubermenu-submenu-id-1742 ubermenu-submenu-type-auto ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-full_width ubermenu-autoclear">
							  <li id="menu-item-1743" class="text-style ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-has-children ubermenu-item-1743 ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-1-3 ubermenu-has-submenu-stack">
								 <span class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only ubermenu-noindicator submenu-heading"><span class="ubermenu-target-title ubermenu-target-text">Cleaning Services</span></span>
								 <ul class="ubermenu-submenu ubermenu-submenu-id-1743 ubermenu-submenu-type-auto ubermenu-submenu-type-stack">
									<li id="menu-item-2188" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2188 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/carpet-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Carpet Cleaning</span></a></li>
									<li id="menu-item-2187" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2187 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/upholstery-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Upholstery Cleaning</span></a></li>
									<li id="menu-item-2186" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2186 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/area-rug-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Area Rug Cleaning</span></a></li>
									<li id="menu-item-2185" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2185 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/mattress-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Mattress Cleaning</span></a></li>
									<li id="menu-item-2185" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2185 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/oriental-rug-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Oriental Rug Cleaning</span></a></li>
								</ul>
							  </li>
							  <li id="menu-item-3203" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-has-children ubermenu-item-3203 ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-1-3 ubermenu-has-submenu-stack">
								 <a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only submenu-heading-2" href="#"><span class="ubermenu-target-title ubermenu-target-text">Level 1</span></a>
								 <ul class="ubermenu-submenu ubermenu-submenu-id-3203 ubermenu-submenu-type-auto ubermenu-submenu-type-stack">
									<li id="menu-item-2600" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2600 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/green-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Green Cleaning</span></a></li>
									<li id="menu-item-2184" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2184 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/commercial-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Commercial Cleaning</span></a></li>
									<li id="menu-item-2183" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2183 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/couch-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Couch Cleaning</span></a></li>
									<li id="menu-item-2183" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2183 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/auto-interior-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Auto Interior Cleaning</span></a></li>
									<li id="menu-item-2183" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-service ubermenu-item-2183 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="/services/pet-stains-odors-cleaning"><i class="ubermenu-icon fa fa-angle-right"></i><span class="ubermenu-target-title ubermenu-target-text">Pet Stains And Odors<br>Cleaning</span></a></li>
								</ul>
							  </li>
							  <li id="menu-item-1767" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-1767 ubermenu-item-header ubermenu-item-level-1 ubermenu-column ubermenu-column-1-3 ubermenu-has-submenu-stack">
								 <a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only submenu-heading-3" href="#"><span class="ubermenu-target-title ubermenu-target-text">Image</span></a>
								 <ul class="ubermenu-submenu ubermenu-submenu-id-1767 ubermenu-submenu-type-auto ubermenu-submenu-type-stack">
									<li id="menu-item-2032" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-2032 ubermenu-item-header ubermenu-item-level-2 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-target-with-image ubermenu-item-layout-default ubermenu-item-layout-image_left menuservices-badge ubermenu-item-notext" href="/"><img class="ubermenu-image ubermenu-image-size-medium" src="/assets/icons/Carpet-Upholstery-Cleaning-Google-Yelp-Rating.png" width="300" height="265" alt="Carpet Upholstery Cleaning Google Yelp Rating"></a></li>
								 </ul>
							  </li>
							  <li class="ubermenu-retractor ubermenu-retractor-mobile"><i class='fa'>&#xf017;</i> Close</li>
						   </ul>
						</li>
						 <li id="menu-item-2459" class="quote_item ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-2459 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="/free-quote" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Request a Quote</span></a></li>
						
						<li id="menu-item-2460" class="service_areas_item ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-2460 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="/service-areas" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Service Areas</span></a></li>
						
						<!--<li id="menu-item-3677" class="reviews_item ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-3677 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="/reviews" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Reviews</span></a></li>-->
						<li id="menu-item-3677" class="reviews_item ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-3677 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="/gallery" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Gallery</span></a></li>
						<li id="menu-item-2454" class="contact_item ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-2454 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto"><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="/contact-us" tabindex="0"><span class="ubermenu-target-title ubermenu-target-text">Contact Us</span></a></li>
					 </ul>
				  </nav>
			   </div>
			</div>


		</div>

